---
# tasks file for nginx
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install required software
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - nginx
    - python-mysqldb

- name: Replace nginx default conf
  template: src=default dest=/etc/nginx/sites-available/default
  notify:
    - restart nginx

