---
# tasks file for wordpress
# tasks file for wordpress
- name: Download WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no
  sudo: yes

- name: Creates directory
  file: path=/var/www/{{ domain }} state=directory

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/{{ domain }}/ copy=no
  sudo: yes


- name: Copy sample config file
  command: mv /var/www/{{ domain }}/wordpress/wp-config-sample.php /var/www/{{ domain }}/wordpress/wp-config.php creates=/var/www/{{ domain }}/wordpress/wp-config.php
  sudo: yes

- name: Update WordPress config file
  lineinfile:
    dest=/var/www/{{ domain }}/wordpress/wp-config.php
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{lookup('password', 'passwordfile')}}');"}
  sudo: yes

  notify:
    - restart nginx
